CREATE TYPE "meal_intention_type" AS ENUM (
  'attend',
  'absent',
  'extra_guest'
);

CREATE TYPE "demand_status_type" AS ENUM (
  'draft',
  'confirmed',
  'locked'
);

CREATE TYPE "change_type_enum" AS ENUM (
  'add',
  'cancel',
  'modify_quantity',
  'absence',
  'extra_guest'
);

CREATE TYPE "approval_status_enum" AS ENUM (
  'pending',
  'approved',
  'rejected'
);

CREATE TYPE "calculation_method_enum" AS ENUM (
  'auto',
  'manual'
);

CREATE TABLE "meal_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "name" varchar,
  "start_time" time,
  "end_time" time,
  "registration_cutoff_time" time,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "classes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_name" varchar,
  "grade_level" varchar,
  "school_year" varchar
);

CREATE TABLE "students" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_code" varchar UNIQUE,
  "full_name" varchar,
  "class_id" integer,
  "status" varchar
);

CREATE TABLE "meal_registrations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer,
  "meal_session_id" integer,
  "effective_from" date,
  "effective_to" date,
  "status" varchar
);

CREATE TABLE "menus" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "menu_date" date,
  "meal_session_id" integer,
  "status" varchar
);

CREATE TABLE "dishes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dish_name" varchar,
  "category" varchar
);

CREATE TABLE "menu_dishes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "menu_id" integer,
  "dish_id" integer,
  "standard_portion_size" decimal,
  "unit" varchar
);

CREATE TABLE "daily_meal_demands" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "demand_date" date,
  "meal_session_id" integer,
  "class_id" integer,
  "base_registered_count" integer,
  "confirmed_attend_count" integer,
  "absence_count" integer DEFAULT 0,
  "extra_count" integer DEFAULT 0,
  "determination_status" demand_status_type DEFAULT 'draft',
  "determined_by" integer,
  "determined_at" datetime,
  "locked_at" datetime
);

CREATE TABLE "daily_meal_demand_details" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "daily_meal_demand_id" integer,
  "student_id" integer,
  "intention" meal_intention_type,
  "reason" varchar,
  "reported_by" integer,
  "reported_at" datetime,
  "is_within_cutoff" boolean
);

CREATE TABLE "expected_meal_quantities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "daily_meal_demand_id" integer,
  "menu_dish_id" integer,
  "planned_headcount" integer,
  "unit_portion_size" decimal,
  "unit" varchar,
  "buffer_percentage" decimal DEFAULT 0,
  "total_quantity" decimal,
  "calculation_method" calculation_method_enum DEFAULT 'auto',
  "calculated_by" integer,
  "calculated_at" datetime
);

CREATE TABLE "meal_demand_change_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "daily_meal_demand_id" integer,
  "student_id" integer,
  "change_type" change_type_enum,
  "requested_quantity_delta" integer,
  "reason" varchar,
  "requested_by" integer,
  "requested_at" datetime,
  "is_emergency" boolean DEFAULT false,
  "approval_status" approval_status_enum DEFAULT 'pending',
  "approved_by" integer,
  "approved_at" datetime
);

CREATE TABLE "meal_demand_change_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "change_request_id" integer,
  "daily_meal_demand_id" integer,
  "field_changed" varchar,
  "old_value" varchar,
  "new_value" varchar,
  "changed_by" integer,
  "changed_at" datetime,
  "note" varchar
);

CREATE UNIQUE INDEX "uq_demand_date_session_class" ON "daily_meal_demands" ("demand_date", "meal_session_id", "class_id");

CREATE UNIQUE INDEX "uq_demand_student" ON "daily_meal_demand_details" ("daily_meal_demand_id", "student_id");

CREATE UNIQUE INDEX "uq_demand_menudish" ON "expected_meal_quantities" ("daily_meal_demand_id", "menu_dish_id");

COMMENT ON COLUMN "meal_sessions"."code" IS 'breakfast/lunch/snack/dinner';

COMMENT ON COLUMN "meal_sessions"."registration_cutoff_time" IS 'cutoff time for reporting attendance/changes before the meal session';

COMMENT ON COLUMN "students"."status" IS 'active/inactive/transferred';

COMMENT ON COLUMN "meal_registrations"."status" IS 'active/suspended/cancelled - owned by Student Meal Management';

COMMENT ON COLUMN "menus"."status" IS 'draft/approved/published - owned by Meal Planning & Menu Management';

COMMENT ON COLUMN "menu_dishes"."standard_portion_size" IS 'standard portion size per recipe/serving';

COMMENT ON COLUMN "daily_meal_demands"."base_registered_count" IS 'number of students on fixed registration (snapshot from meal_registrations)';

COMMENT ON COLUMN "daily_meal_demands"."confirmed_attend_count" IS 'actual confirmed attendance count after adjustments';

COMMENT ON COLUMN "daily_meal_demands"."extra_count" IS 'extra portions: guests, staff, make-up meals';

COMMENT ON COLUMN "daily_meal_demands"."determined_by" IS 'user_id: homeroom teacher/boarding staff';

COMMENT ON COLUMN "daily_meal_demands"."locked_at" IS 'timestamp when data is locked after cutoff_time';

COMMENT ON COLUMN "daily_meal_demand_details"."reported_by" IS 'user_id: parent/homeroom teacher';

COMMENT ON COLUMN "daily_meal_demand_details"."is_within_cutoff" IS 'true if reported before the meal_session cutoff time';

COMMENT ON COLUMN "expected_meal_quantities"."planned_headcount" IS '= confirmed_attend_count + extra_count at calculation time';

COMMENT ON COLUMN "expected_meal_quantities"."unit_portion_size" IS 'copied from menu_dishes.standard_portion_size';

COMMENT ON COLUMN "expected_meal_quantities"."buffer_percentage" IS 'buffer % for shrinkage/surplus';

COMMENT ON COLUMN "expected_meal_quantities"."total_quantity" IS 'planned_headcount * unit_portion_size * (1 + buffer_percentage)';

COMMENT ON COLUMN "expected_meal_quantities"."calculated_by" IS 'user_id, null if calculated automatically by the system';

COMMENT ON COLUMN "meal_demand_change_requests"."student_id" IS 'null if the change applies at class/aggregate level';

COMMENT ON COLUMN "meal_demand_change_requests"."requested_quantity_delta" IS 'number of portions changed (+/-)';

COMMENT ON COLUMN "meal_demand_change_requests"."requested_by" IS 'user_id';

COMMENT ON COLUMN "meal_demand_change_requests"."is_emergency" IS 'true if raised after registration_cutoff_time';

COMMENT ON COLUMN "meal_demand_change_logs"."field_changed" IS 'e.g. confirmed_attend_count, extra_count, total_quantity';

COMMENT ON COLUMN "meal_demand_change_logs"."changed_by" IS 'user_id';

ALTER TABLE "students" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_registrations" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_registrations" ADD FOREIGN KEY ("meal_session_id") REFERENCES "meal_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menus" ADD FOREIGN KEY ("meal_session_id") REFERENCES "meal_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_dishes" ADD FOREIGN KEY ("menu_id") REFERENCES "menus" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_dishes" ADD FOREIGN KEY ("dish_id") REFERENCES "dishes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "daily_meal_demands" ADD FOREIGN KEY ("meal_session_id") REFERENCES "meal_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "daily_meal_demands" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "daily_meal_demand_details" ADD FOREIGN KEY ("daily_meal_demand_id") REFERENCES "daily_meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "daily_meal_demand_details" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expected_meal_quantities" ADD FOREIGN KEY ("daily_meal_demand_id") REFERENCES "daily_meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expected_meal_quantities" ADD FOREIGN KEY ("menu_dish_id") REFERENCES "menu_dishes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_change_requests" ADD FOREIGN KEY ("daily_meal_demand_id") REFERENCES "daily_meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_change_requests" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_change_logs" ADD FOREIGN KEY ("change_request_id") REFERENCES "meal_demand_change_requests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_change_logs" ADD FOREIGN KEY ("daily_meal_demand_id") REFERENCES "daily_meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;
