CREATE TYPE "meal_type_enum" AS ENUM (
  'breakfast',
  'lunch',
  'dinner',
  'snack'
);

CREATE TYPE "participation_status_enum" AS ENUM (
  'pending',
  'recorded',
  'confirmed',
  'cancelled'
);

CREATE TYPE "participation_change_type_enum" AS ENUM (
  'status_update',
  'correction',
  'reschedule'
);

CREATE TYPE "demand_determination_method_enum" AS ENUM (
  'participation_based',
  'manual_forecast',
  'historical_average'
);

CREATE TYPE "demand_status_enum" AS ENUM (
  'draft',
  'calculated',
  'confirmed',
  'revised'
);

CREATE TYPE "demand_change_type_enum" AS ENUM (
  'quantity_increase',
  'quantity_decrease',
  'dish_adjustment',
  'cancellation'
);

CREATE TYPE "prep_plan_status_enum" AS ENUM (
  'planned',
  'in_progress',
  'completed',
  'cancelled'
);

CREATE TYPE "allocation_status_enum" AS ENUM (
  'allocated',
  'adjusted',
  'returned'
);

CREATE TYPE "prep_record_status_enum" AS ENUM (
  'in_progress',
  'completed'
);

CREATE TYPE "confirmation_status_enum" AS ENUM (
  'matched',
  'discrepancy'
);

CREATE TABLE "students" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "class_name" varchar,
  "eligibility_status" varchar
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "role" varchar
);

CREATE TABLE "meal_schedules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_date" date,
  "meal_type" meal_type_enum,
  "menu_id" integer
);

CREATE TABLE "dishes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "status" varchar
);

CREATE TABLE "ingredients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "unit" varchar
);

CREATE TABLE "meal_registrations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer,
  "meal_schedule_id" integer,
  "status" varchar
);

CREATE TABLE "meal_participations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer NOT NULL,
  "meal_schedule_id" integer NOT NULL,
  "meal_registration_id" integer,
  "meal_date" date NOT NULL,
  "meal_type" meal_type_enum NOT NULL,
  "status" participation_status_enum NOT NULL DEFAULT 'pending',
  "recorded_by" integer,
  "recorded_at" datetime,
  "confirmed_by" integer,
  "confirmed_at" datetime,
  "notes" varchar,
  "created_at" datetime DEFAULT (now()),
  "updated_at" datetime
);

CREATE TABLE "meal_participation_changes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_participation_id" integer NOT NULL,
  "change_type" participation_change_type_enum NOT NULL,
  "old_status" participation_status_enum,
  "new_status" participation_status_enum,
  "reason" varchar,
  "changed_by" integer NOT NULL,
  "changed_at" datetime DEFAULT (now())
);

CREATE TABLE "meal_demands" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_schedule_id" integer NOT NULL,
  "meal_date" date NOT NULL,
  "meal_type" meal_type_enum NOT NULL,
  "determined_quantity" integer NOT NULL,
  "determination_method" demand_determination_method_enum NOT NULL DEFAULT 'participation_based',
  "status" demand_status_enum NOT NULL DEFAULT 'draft',
  "determined_by" integer,
  "determined_at" datetime,
  "confirmed_by" integer,
  "confirmed_at" datetime,
  "created_at" datetime DEFAULT (now()),
  "updated_at" datetime
);

CREATE TABLE "meal_demand_dish_quantities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_demand_id" integer NOT NULL,
  "dish_id" integer NOT NULL,
  "expected_quantity" decimal NOT NULL,
  "unit" varchar NOT NULL,
  "calculated_by" integer,
  "calculated_at" datetime DEFAULT (now())
);

CREATE TABLE "meal_demand_changes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_demand_id" integer NOT NULL,
  "change_type" demand_change_type_enum NOT NULL,
  "old_quantity" integer,
  "new_quantity" integer,
  "reason" varchar,
  "changed_by" integer NOT NULL,
  "changed_at" datetime DEFAULT (now())
);

CREATE TABLE "meal_preparation_plans" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_demand_id" integer NOT NULL,
  "meal_schedule_id" integer NOT NULL,
  "planned_date" date NOT NULL,
  "meal_type" meal_type_enum NOT NULL,
  "status" prep_plan_status_enum NOT NULL DEFAULT 'planned',
  "planned_by" integer,
  "planned_at" datetime DEFAULT (now())
);

CREATE TABLE "meal_preparation_plan_dishes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "preparation_plan_id" integer NOT NULL,
  "dish_id" integer NOT NULL,
  "planned_quantity" decimal NOT NULL,
  "unit" varchar NOT NULL
);

CREATE TABLE "ingredient_allocations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "preparation_plan_id" integer NOT NULL,
  "ingredient_id" integer NOT NULL,
  "allocated_quantity" decimal NOT NULL,
  "unit" varchar NOT NULL,
  "status" allocation_status_enum NOT NULL DEFAULT 'allocated',
  "allocated_by" integer,
  "allocated_at" datetime DEFAULT (now()),
  "notes" varchar
);

CREATE TABLE "meal_preparations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "preparation_plan_id" integer NOT NULL,
  "prepared_by" integer,
  "status" prep_record_status_enum NOT NULL DEFAULT 'in_progress',
  "started_at" datetime,
  "completed_at" datetime,
  "notes" varchar
);

CREATE TABLE "meal_preparation_dish_records" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_preparation_id" integer NOT NULL,
  "dish_id" integer NOT NULL,
  "prepared_quantity" decimal NOT NULL,
  "unit" varchar NOT NULL,
  "recorded_at" datetime DEFAULT (now())
);

CREATE TABLE "prepared_quantity_confirmations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_preparation_dish_record_id" integer NOT NULL,
  "confirmed_quantity" decimal NOT NULL,
  "confirmation_status" confirmation_status_enum NOT NULL,
  "discrepancy_reason" varchar,
  "confirmed_by" integer NOT NULL,
  "confirmed_at" datetime DEFAULT (now())
);

CREATE UNIQUE INDEX "uq_student_meal_schedule" ON "meal_participations" ("student_id", "meal_schedule_id");

CREATE INDEX ON "meal_participations" ("meal_date", "meal_type");

CREATE UNIQUE INDEX ON "meal_demands" ("meal_schedule_id");

CREATE UNIQUE INDEX "uq_demand_dish" ON "meal_demand_dish_quantities" ("meal_demand_id", "dish_id");

CREATE UNIQUE INDEX ON "meal_preparation_plans" ("meal_demand_id");

CREATE UNIQUE INDEX "uq_plan_dish" ON "meal_preparation_plan_dishes" ("preparation_plan_id", "dish_id");

CREATE UNIQUE INDEX ON "meal_preparations" ("preparation_plan_id");

CREATE UNIQUE INDEX "uq_prep_dish" ON "meal_preparation_dish_records" ("meal_preparation_id", "dish_id");

COMMENT ON TABLE "students" IS 'Simplified reference - see Student Meal Eligibility Management';

COMMENT ON TABLE "users" IS 'Staff / kitchen users performing actions';

COMMENT ON TABLE "meal_schedules" IS 'Simplified reference - see Meal Schedule Management';

COMMENT ON TABLE "dishes" IS 'Simplified reference - see Dish Management';

COMMENT ON TABLE "ingredients" IS 'Simplified reference - see Inventory Management';

COMMENT ON TABLE "meal_registrations" IS 'Simplified reference - see Meal Registration Management';

COMMENT ON TABLE "meal_participations" IS 'Records that a student actually took part in a specific meal (Record / Confirm Meal Participation)';

COMMENT ON TABLE "meal_participation_changes" IS 'Audit trail for Manage Participation Changes';

COMMENT ON TABLE "meal_demands" IS 'Determine Meal Demand - aggregated from confirmed meal_participations for that meal_schedule';

COMMENT ON COLUMN "meal_demands"."determined_quantity" IS 'total headcount / servings determined';

COMMENT ON TABLE "meal_demand_dish_quantities" IS 'Calculate Expected Meal Quantity per dish (determined_quantity x recipe portion size)';

COMMENT ON TABLE "meal_demand_changes" IS 'Audit trail for Manage Meal Demand & Quantity Changes';

COMMENT ON TABLE "meal_preparation_plans" IS 'Plan Meal Preparation, built from a confirmed meal_demand';

COMMENT ON TABLE "meal_preparation_plan_dishes" IS 'Dish-level breakdown of a preparation plan, seeded from meal_demand_dish_quantities';

COMMENT ON TABLE "ingredient_allocations" IS 'Manage Ingredient Allocation - ingredients reserved from inventory for a preparation plan';

COMMENT ON TABLE "meal_preparations" IS 'Record Meal Preparation - actual cooking execution against a plan';

COMMENT ON TABLE "meal_preparation_dish_records" IS 'Actual quantity prepared per dish';

COMMENT ON TABLE "prepared_quantity_confirmations" IS 'Confirm Prepared Quantity - verification step comparing planned vs prepared vs confirmed';

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("meal_schedule_id") REFERENCES "meal_schedules" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("meal_registration_id") REFERENCES "meal_registrations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("recorded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("confirmed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participation_changes" ADD FOREIGN KEY ("meal_participation_id") REFERENCES "meal_participations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participation_changes" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demands" ADD FOREIGN KEY ("meal_schedule_id") REFERENCES "meal_schedules" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demands" ADD FOREIGN KEY ("determined_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demands" ADD FOREIGN KEY ("confirmed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_dish_quantities" ADD FOREIGN KEY ("meal_demand_id") REFERENCES "meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_dish_quantities" ADD FOREIGN KEY ("dish_id") REFERENCES "dishes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_dish_quantities" ADD FOREIGN KEY ("calculated_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_changes" ADD FOREIGN KEY ("meal_demand_id") REFERENCES "meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_changes" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_preparation_plans" ADD FOREIGN KEY ("meal_demand_id") REFERENCES "meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_preparation_plans" ADD FOREIGN KEY ("meal_schedule_id") REFERENCES "meal_schedules" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_preparation_plans" ADD FOREIGN KEY ("planned_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_preparation_plan_dishes" ADD FOREIGN KEY ("preparation_plan_id") REFERENCES "meal_preparation_plans" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_preparation_plan_dishes" ADD FOREIGN KEY ("dish_id") REFERENCES "dishes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ingredient_allocations" ADD FOREIGN KEY ("preparation_plan_id") REFERENCES "meal_preparation_plans" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ingredient_allocations" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ingredient_allocations" ADD FOREIGN KEY ("allocated_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_preparations" ADD FOREIGN KEY ("preparation_plan_id") REFERENCES "meal_preparation_plans" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_preparations" ADD FOREIGN KEY ("prepared_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_preparation_dish_records" ADD FOREIGN KEY ("meal_preparation_id") REFERENCES "meal_preparations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_preparation_dish_records" ADD FOREIGN KEY ("dish_id") REFERENCES "dishes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prepared_quantity_confirmations" ADD FOREIGN KEY ("meal_preparation_dish_record_id") REFERENCES "meal_preparation_dish_records" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prepared_quantity_confirmations" ADD FOREIGN KEY ("confirmed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
