CREATE TYPE "meal_type_enum" AS ENUM (
  'lunch'
);

CREATE TYPE "fixed_role_enum" AS ENUM (
  'ADM',
  'MGR',
  'ACC',
  'PAR'
);

CREATE TYPE "eligibility_status_enum" AS ENUM (
  'eligible',
  'ineligible',
  'pending_review'
);

CREATE TYPE "registration_status_enum" AS ENUM (
  'active',
  'on_leave',
  'cancelled'
);

CREATE TYPE "participation_status_enum" AS ENUM (
  'present',
  'absent_excused',
  'absent_unexcused'
);

CREATE TYPE "participation_change_type_enum" AS ENUM (
  'status_update',
  'absence_logging',
  'emergency_correction'
);

CREATE TYPE "menu_approval_status_enum" AS ENUM (
  'draft',
  'submitted',
  'approved',
  'rejected'
);

CREATE TYPE "dish_course_type_enum" AS ENUM (
  'main_entree',
  'side_dish',
  'soup',
  'dessert'
);

CREATE TYPE "allergen_type_enum" AS ENUM (
  'peanut',
  'tree_nut',
  'seafood',
  'shellfish',
  'egg',
  'cow_milk',
  'soy',
  'wheat_gluten',
  'other'
);

CREATE TYPE "allergy_severity_enum" AS ENUM (
  'mild',
  'moderate',
  'severe_anaphylaxis'
);

CREATE TYPE "demand_determination_method_enum" AS ENUM (
  'attendance_based',
  'historical_forecast',
  'manual_adjustment'
);

CREATE TYPE "demand_status_enum" AS ENUM (
  'draft',
  'calculated',
  'confirmed',
  'revised'
);

CREATE TYPE "demand_change_type_enum" AS ENUM (
  'quantity_increase',
  'quantity_decrease',
  'dish_adjustment',
  'cancellation'
);

CREATE TYPE "catering_order_status_enum" AS ENUM (
  'draft',
  'dispatched',
  'acknowledged',
  'delivered',
  'cancelled'
);

CREATE TYPE "delivery_status_enum" AS ENUM (
  'arrived',
  'inspecting',
  'accepted',
  'rejected'
);

CREATE TYPE "inspection_result_enum" AS ENUM (
  'passed',
  'rejected',
  'conditional_acceptance'
);

CREATE TYPE "distribution_status_enum" AS ENUM (
  'preparing',
  'dispatched_to_class',
  'delivered'
);

CREATE TYPE "reconciliation_variance_type_enum" AS ENUM (
  'exact_match',
  'vendor_shortfall',
  'excess_leftover',
  'damaged_spillage'
);

CREATE TYPE "bill_status_enum" AS ENUM (
  'unpaid',
  'partial',
  'paid'
);

CREATE TYPE "payment_method_enum" AS ENUM (
  'vietqr_bank_transfer',
  'cash',
  'bank_transfer_manual'
);

CREATE TABLE "school_years" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "is_active" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "semesters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_year_id" integer NOT NULL,
  "code" varchar(20) NOT NULL,
  "name" varchar(100) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "is_active" boolean NOT NULL DEFAULT false
);

CREATE TABLE "grades" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grade_level" integer UNIQUE NOT NULL,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "classes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_year_id" integer NOT NULL,
  "grade_id" integer NOT NULL,
  "name" varchar(50) NOT NULL,
  "homeroom_teacher_id" integer,
  "classroom_location" varchar(100),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "students" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_code" varchar(50) UNIQUE NOT NULL,
  "full_name" varchar(150) NOT NULL,
  "date_of_birth" date NOT NULL,
  "gender" varchar(10),
  "current_class_id" integer NOT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'active',
  "dietary_notes" varchar(500),
  "has_severe_allergy" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "meal_calendars" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "calendar_date" date UNIQUE NOT NULL,
  "is_serving_day" boolean NOT NULL DEFAULT true,
  "description" varchar(255)
);

CREATE TABLE "holidays" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_year_id" integer NOT NULL,
  "name" varchar(150) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "description" varchar(255)
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" fixed_role_enum UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" varchar(255)
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "full_name" varchar(150) NOT NULL,
  "phone" varchar(30),
  "role_id" integer NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_login_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "parent_student_associations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_user_id" integer NOT NULL,
  "student_id" integer NOT NULL,
  "relationship_type" varchar(50) NOT NULL DEFAULT 'parent',
  "is_primary_contact" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "student_allergies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer NOT NULL,
  "allergen_type" allergen_type_enum NOT NULL,
  "allergen_name" varchar(100) NOT NULL,
  "severity" allergy_severity_enum NOT NULL DEFAULT 'moderate',
  "medical_action_plan" text,
  "diagnosed_by" varchar(150),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "ingredients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL,
  "allergen_type" allergen_type_enum,
  "description" varchar(255)
);

CREATE TABLE "dishes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL,
  "course_type" dish_course_type_enum NOT NULL,
  "standard_portion_weight" decimal(8,2) NOT NULL,
  "unit" varchar(30) NOT NULL DEFAULT 'grams',
  "calories_kcal" decimal(6,2),
  "status" varchar(30) NOT NULL DEFAULT 'active',
  "description" text,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "dish_ingredients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dish_id" integer NOT NULL,
  "ingredient_id" integer NOT NULL,
  "is_mandatory" boolean NOT NULL DEFAULT true
);

CREATE TABLE "menus" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_year_id" integer NOT NULL,
  "week_number" integer NOT NULL,
  "name" varchar(150) NOT NULL,
  "approval_status" menu_approval_status_enum NOT NULL DEFAULT 'draft',
  "created_by" integer NOT NULL,
  "approved_by" integer,
  "approved_at" timestamp,
  "rejection_reason" varchar(500),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "menu_dishes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "menu_id" integer NOT NULL,
  "day_of_week" integer NOT NULL,
  "dish_id" integer NOT NULL
);

CREATE TABLE "meal_schedules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_date" date UNIQUE NOT NULL,
  "meal_type" meal_type_enum NOT NULL DEFAULT 'lunch',
  "menu_id" integer NOT NULL,
  "cutoff_time" time NOT NULL DEFAULT '08:30:00',
  "order_deadline_time" time NOT NULL DEFAULT '08:45:00',
  "dock_arrival_time" time NOT NULL DEFAULT '10:30:00',
  "distribution_time" time NOT NULL DEFAULT '11:00:00',
  "reconciliation_time" time NOT NULL DEFAULT '13:00:00',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "meal_eligibility_criteria" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_year_id" integer NOT NULL,
  "name" varchar(150) NOT NULL,
  "min_grade" integer NOT NULL DEFAULT 1,
  "max_grade" integer NOT NULL DEFAULT 5,
  "requires_health_clearance" boolean NOT NULL DEFAULT true,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "student_meal_eligibilities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer NOT NULL,
  "criteria_id" integer NOT NULL,
  "status" eligibility_status_enum NOT NULL DEFAULT 'eligible',
  "verified_by" integer,
  "verified_at" timestamp,
  "reason" varchar(255)
);

CREATE TABLE "meal_registrations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer NOT NULL,
  "semester_id" integer NOT NULL,
  "status" registration_status_enum NOT NULL DEFAULT 'active',
  "dietary_notes" varchar(500),
  "registered_by" integer NOT NULL,
  "registered_at" timestamp NOT NULL DEFAULT (now()),
  "cancelled_at" timestamp
);

CREATE TABLE "meal_participations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer NOT NULL,
  "meal_schedule_id" integer NOT NULL,
  "class_id" integer NOT NULL,
  "meal_registration_id" integer,
  "status" participation_status_enum NOT NULL DEFAULT 'present',
  "is_locked" boolean NOT NULL DEFAULT false,
  "recorded_by" integer NOT NULL,
  "recorded_at" timestamp NOT NULL DEFAULT (now()),
  "notes" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "meal_participation_changes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_participation_id" integer NOT NULL,
  "change_type" participation_change_type_enum NOT NULL,
  "old_status" participation_status_enum NOT NULL,
  "new_status" participation_status_enum NOT NULL,
  "reason" varchar(500) NOT NULL,
  "changed_by" integer NOT NULL,
  "changed_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "meal_demands" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_schedule_id" integer UNIQUE NOT NULL,
  "confirmed_attendance" integer NOT NULL,
  "special_dietary_count" integer NOT NULL DEFAULT 0,
  "buffer_rate" decimal(4,3) NOT NULL DEFAULT 0.05,
  "buffer_quantity" integer NOT NULL,
  "final_demand_count" integer NOT NULL,
  "determination_method" demand_determination_method_enum NOT NULL DEFAULT 'attendance_based',
  "status" demand_status_enum NOT NULL DEFAULT 'draft',
  "determined_by" integer NOT NULL,
  "determined_at" timestamp NOT NULL DEFAULT (now()),
  "confirmed_by" integer,
  "confirmed_at" timestamp
);

CREATE TABLE "meal_demand_dish_quantities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_demand_id" integer NOT NULL,
  "dish_id" integer NOT NULL,
  "expected_quantity" decimal(10,2) NOT NULL,
  "unit" varchar(30) NOT NULL,
  "calculated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "meal_demand_changes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_demand_id" integer NOT NULL,
  "change_type" demand_change_type_enum NOT NULL,
  "old_quantity" integer NOT NULL,
  "new_quantity" integer NOT NULL,
  "reason" varchar(500) NOT NULL,
  "changed_by" integer NOT NULL,
  "changed_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "catering_orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_code" varchar(50) UNIQUE NOT NULL,
  "meal_demand_id" integer UNIQUE NOT NULL,
  "vendor_name" varchar(150) NOT NULL DEFAULT 'Licensed Catering Partner',
  "total_ordered_portions" integer NOT NULL,
  "standard_portions" integer NOT NULL,
  "special_dietary_portions" integer NOT NULL,
  "target_delivery_time" timestamp NOT NULL,
  "status" catering_order_status_enum NOT NULL DEFAULT 'draft',
  "dispatched_at" timestamp,
  "dispatched_by" integer,
  "vendor_acknowledged_at" timestamp,
  "vendor_tracking_reference" varchar(100),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "meal_deliveries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "catering_order_id" integer UNIQUE NOT NULL,
  "arrival_time" timestamp NOT NULL DEFAULT (now()),
  "vehicle_plate" varchar(30) NOT NULL,
  "driver_name" varchar(100),
  "thermal_container_count" integer NOT NULL,
  "delivered_portions" integer NOT NULL,
  "received_by" integer NOT NULL,
  "status" delivery_status_enum NOT NULL DEFAULT 'arrived',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "meal_inspections" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_delivery_id" integer UNIQUE NOT NULL,
  "inspector_id" integer NOT NULL,
  "core_temperature" decimal(4,1) NOT NULL,
  "container_seals_intact" boolean NOT NULL,
  "sensory_eval_pass" boolean NOT NULL,
  "retention_sample_taken" boolean NOT NULL DEFAULT true,
  "sample_photo_url" varchar(500),
  "thermometer_photo_url" varchar(500),
  "inspection_result" inspection_result_enum NOT NULL,
  "rejection_reason" varchar(500),
  "inspected_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "meal_distributions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_delivery_id" integer NOT NULL,
  "class_id" integer NOT NULL,
  "allocated_portions" integer NOT NULL,
  "special_dietary_portions" integer NOT NULL DEFAULT 0,
  "distributed_at" timestamp NOT NULL DEFAULT (now()),
  "distributed_by" integer NOT NULL,
  "received_by_teacher_id" integer,
  "status" distribution_status_enum NOT NULL DEFAULT 'delivered'
);

CREATE TABLE "meal_reconciliations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "catering_order_id" integer UNIQUE NOT NULL,
  "ordered_quantity" integer NOT NULL,
  "delivered_quantity" integer NOT NULL,
  "consumed_quantity" integer NOT NULL,
  "leftover_quantity" integer NOT NULL,
  "delivery_variance" integer NOT NULL,
  "consumption_variance" integer NOT NULL,
  "accepted_payable_quantity" integer NOT NULL,
  "variance_type" reconciliation_variance_type_enum NOT NULL DEFAULT 'exact_match',
  "reconciled_by" integer NOT NULL,
  "reconciled_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "meal_discrepancies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_reconciliation_id" integer NOT NULL,
  "discrepancy_count" integer NOT NULL,
  "discrepancy_reason" varchar(500) NOT NULL,
  "financial_impact_note" varchar(255),
  "resolved_by" integer NOT NULL,
  "resolved_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "meal_fee_configs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_year_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "meal_fee_rate" decimal(10,2) NOT NULL,
  "caterer_cost_rate" decimal(10,2) NOT NULL,
  "effective_from" date NOT NULL,
  "effective_to" date NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_by" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "student_meal_bills" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer NOT NULL,
  "fee_config_id" integer NOT NULL,
  "billing_month" varchar(7) NOT NULL,
  "total_scheduled_meals" integer NOT NULL,
  "attended_meals" integer NOT NULL,
  "credited_absences" integer NOT NULL,
  "unexcused_absences" integer NOT NULL,
  "total_chargeable_meals" integer NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "total_amount" decimal(12,2) NOT NULL,
  "paid_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "payment_status" bill_status_enum NOT NULL DEFAULT 'unpaid',
  "vietqr_payload" varchar(500),
  "issued_at" timestamp NOT NULL DEFAULT (now()),
  "due_date" date NOT NULL
);

CREATE TABLE "student_billing_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_meal_bill_id" integer NOT NULL,
  "meal_schedule_id" integer NOT NULL,
  "meal_participation_id" integer,
  "is_charged" boolean NOT NULL,
  "credit_reason" varchar(255)
);

CREATE TABLE "meal_payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_meal_bill_id" integer NOT NULL,
  "payment_code" varchar(50) UNIQUE NOT NULL,
  "amount" decimal(12,2) NOT NULL,
  "payment_method" payment_method_enum NOT NULL DEFAULT 'vietqr_bank_transfer',
  "transaction_reference" varchar(100),
  "recorded_by" integer,
  "paid_at" timestamp NOT NULL DEFAULT (now()),
  "notes" varchar(255)
);

CREATE TABLE "vendor_payables" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fee_config_id" integer NOT NULL,
  "catering_order_id" integer UNIQUE NOT NULL,
  "reconciled_billable_portions" integer NOT NULL,
  "unit_cost" decimal(10,2) NOT NULL,
  "total_payable_amount" decimal(12,2) NOT NULL,
  "is_settled" boolean NOT NULL DEFAULT false,
  "settled_at" timestamp,
  "settlement_reference" varchar(100),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX "uq_semester_year_code" ON "semesters" ("school_year_id", "code");

CREATE UNIQUE INDEX "uq_class_year_name" ON "classes" ("school_year_id", "name");

CREATE INDEX ON "students" ("current_class_id");

CREATE INDEX ON "students" ("student_code");

CREATE INDEX ON "meal_calendars" ("calendar_date");

CREATE INDEX ON "holidays" ("start_date", "end_date");

CREATE INDEX ON "users" ("role_id");

CREATE INDEX ON "users" ("email");

CREATE UNIQUE INDEX "uq_parent_student" ON "parent_student_associations" ("parent_user_id", "student_id");

CREATE UNIQUE INDEX "uq_student_allergen" ON "student_allergies" ("student_id", "allergen_type");

CREATE INDEX ON "dishes" ("course_type");

CREATE UNIQUE INDEX "uq_dish_ingredient" ON "dish_ingredients" ("dish_id", "ingredient_id");

CREATE UNIQUE INDEX "uq_menu_year_week" ON "menus" ("school_year_id", "week_number");

CREATE UNIQUE INDEX "uq_menu_day_dish" ON "menu_dishes" ("menu_id", "day_of_week", "dish_id");

CREATE INDEX ON "meal_schedules" ("meal_date");

CREATE UNIQUE INDEX "uq_student_criteria" ON "student_meal_eligibilities" ("student_id", "criteria_id");

CREATE UNIQUE INDEX "uq_student_semester_reg" ON "meal_registrations" ("student_id", "semester_id");

CREATE UNIQUE INDEX "uq_student_meal_schedule" ON "meal_participations" ("student_id", "meal_schedule_id");

CREATE INDEX ON "meal_participations" ("meal_schedule_id", "class_id");

CREATE INDEX ON "meal_participations" ("meal_schedule_id", "status");

CREATE INDEX ON "meal_participation_changes" ("meal_participation_id");

CREATE INDEX ON "meal_demands" ("meal_schedule_id");

CREATE UNIQUE INDEX "uq_demand_dish" ON "meal_demand_dish_quantities" ("meal_demand_id", "dish_id");

CREATE INDEX ON "meal_demand_changes" ("meal_demand_id");

CREATE INDEX ON "catering_orders" ("order_code");

CREATE INDEX ON "catering_orders" ("meal_demand_id");

CREATE INDEX ON "meal_deliveries" ("catering_order_id");

CREATE INDEX ON "meal_inspections" ("meal_delivery_id");

CREATE UNIQUE INDEX "uq_delivery_class_distrib" ON "meal_distributions" ("meal_delivery_id", "class_id");

CREATE INDEX ON "meal_reconciliations" ("catering_order_id");

CREATE INDEX ON "meal_discrepancies" ("meal_reconciliation_id");

CREATE INDEX ON "meal_fee_configs" ("school_year_id", "is_active");

CREATE UNIQUE INDEX "uq_student_bill_month" ON "student_meal_bills" ("student_id", "billing_month");

CREATE INDEX ON "student_meal_bills" ("payment_status");

CREATE UNIQUE INDEX "uq_bill_item_schedule" ON "student_billing_items" ("student_meal_bill_id", "meal_schedule_id");

CREATE INDEX ON "meal_payments" ("student_meal_bill_id");

CREATE INDEX ON "meal_payments" ("payment_code");

CREATE INDEX ON "vendor_payables" ("catering_order_id");

CREATE INDEX ON "vendor_payables" ("is_settled");

COMMENT ON TABLE "school_years" IS 'Academic school year definition';

COMMENT ON COLUMN "school_years"."code" IS 'e.g., 2026-2027';

COMMENT ON TABLE "semesters" IS 'Academic semester within a school year';

COMMENT ON COLUMN "semesters"."code" IS 'e.g., SEM1, SEM2';

COMMENT ON TABLE "grades" IS 'Primary school grade level definition';

COMMENT ON COLUMN "grades"."grade_level" IS '1 to 5 for primary school';

COMMENT ON COLUMN "grades"."name" IS 'e.g., Khối 1';

COMMENT ON TABLE "classes" IS 'Classroom entity where morning roll-call and 11:00 AM meal tray delivery occurs';

COMMENT ON COLUMN "classes"."name" IS 'e.g., 1A, 2B, 3C';

COMMENT ON COLUMN "classes"."classroom_location" IS 'Building / room number for meal trolley dispatch';

COMMENT ON TABLE "students" IS 'Master student directory synchronised with School Information System (SIS)';

COMMENT ON COLUMN "students"."student_code" IS 'Official school student registration ID';

COMMENT ON COLUMN "students"."dietary_notes" IS 'General dietary preferences or religious notes';

COMMENT ON COLUMN "students"."has_severe_allergy" IS 'Pre-computed flag to speed up allergen warning lookups';

COMMENT ON TABLE "meal_calendars" IS 'Master calendar governing lunch service eligibility and fee billing day exclusions';

COMMENT ON COLUMN "meal_calendars"."is_serving_day" IS 'Default serving days are Monday through Friday';

COMMENT ON TABLE "holidays" IS 'Institutional and national non-serving holiday periods automatically excluded from billing';

COMMENT ON COLUMN "holidays"."name" IS 'e.g., Tet Holiday, Teacher Day';

COMMENT ON TABLE "roles" IS 'Fixed 4-Role RBAC Model: ADM, MGR, ACC, PAR (no ad-hoc runtime overrides)';

COMMENT ON TABLE "users" IS 'User accounts authenticated via JWT; maps directly to the fixed role model';

COMMENT ON TABLE "parent_student_associations" IS 'Associates parent user accounts with their enrolled children for portal isolation';

COMMENT ON COLUMN "parent_student_associations"."relationship_type" IS 'father, mother, guardian';

COMMENT ON TABLE "student_allergies" IS 'Medical allergy profiles declared by parents or school medical staff for safety alerts';

COMMENT ON COLUMN "student_allergies"."allergen_name" IS 'Specific allergen, e.g., Peanut, Shrimp, Crab, Cow Milk';

COMMENT ON COLUMN "student_allergies"."medical_action_plan" IS 'First aid and emergency protocol if exposed';

COMMENT ON COLUMN "student_allergies"."diagnosed_by" IS 'Doctor / hospital medical certificate reference';

COMMENT ON TABLE "ingredients" IS 'Food ingredients used in menu dishes to evaluate recipe-allergy conflicts';

COMMENT ON COLUMN "ingredients"."allergen_type" IS 'Allergen category if this ingredient triggers allergies';

COMMENT ON TABLE "dishes" IS 'Standard school lunch culinary and nutritional dish catalog';

COMMENT ON COLUMN "dishes"."standard_portion_weight" IS 'Standard portion size per child';

COMMENT ON COLUMN "dishes"."unit" IS 'grams, ml, pieces';

COMMENT ON TABLE "dish_ingredients" IS 'Recipe ingredient composition enabling automated downstream allergen conflict detection';

COMMENT ON TABLE "menus" IS 'Weekly lunch menu subject to single-level approval by School Administrator';

COMMENT ON COLUMN "menus"."week_number" IS 'School calendar week number, 1-52';

COMMENT ON COLUMN "menus"."name" IS 'e.g., Thuc don Tuan 42';

COMMENT ON COLUMN "menus"."approved_by" IS 'Single-level approval by School Administrator / Principal';

COMMENT ON TABLE "menu_dishes" IS 'Assignment of catalog dishes into the weekly menu for each school day';

COMMENT ON COLUMN "menu_dishes"."day_of_week" IS '2=Monday, 3=Tuesday, ..., 6=Friday';

COMMENT ON TABLE "meal_schedules" IS 'Daily meal schedule linking an approved menu with statutory operational timeline milestones';

COMMENT ON COLUMN "meal_schedules"."cutoff_time" IS 'Attendance lock deadline';

COMMENT ON COLUMN "meal_schedules"."order_deadline_time" IS 'Catering PO dispatch deadline';

COMMENT ON COLUMN "meal_schedules"."dock_arrival_time" IS 'Delivery dock receiving window';

COMMENT ON COLUMN "meal_schedules"."distribution_time" IS 'Classroom trolley distribution';

COMMENT ON COLUMN "meal_schedules"."reconciliation_time" IS 'Post-lunch reconciliation window';

COMMENT ON TABLE "meal_eligibility_criteria" IS 'Rules and criteria determining student boarding eligibility';

COMMENT ON TABLE "student_meal_eligibilities" IS 'Evaluation of student boarding program eligibility status';

COMMENT ON TABLE "meal_registrations" IS 'Semester boarding program enrollment binding students to daily attendance rosters';

COMMENT ON TABLE "meal_participations" IS 'Daily classroom lunch attendance record locked at 08:30 AM cutoff';

COMMENT ON COLUMN "meal_participations"."is_locked" IS 'Hard locked at 08:30 AM by AttendanceCutoffGuard';

COMMENT ON COLUMN "meal_participations"."recorded_by" IS 'Homeroom teacher or substitute coordinator taking attendance';

COMMENT ON COLUMN "meal_participations"."notes" IS 'Absence reason: sick leave, family business, etc.';

COMMENT ON TABLE "meal_participation_changes" IS 'Immutable audit trail capturing all attendance amendments post-roll-call';

COMMENT ON COLUMN "meal_participation_changes"."reason" IS 'Mandatory justification for modifying locked attendance';

COMMENT ON TABLE "meal_demands" IS 'Aggregated daily session demand calculation with safety buffer margin';

COMMENT ON COLUMN "meal_demands"."confirmed_attendance" IS 'Aggregated net present students across all classrooms at 08:30 AM';

COMMENT ON COLUMN "meal_demands"."special_dietary_count" IS 'Count of allergy-free or vegetarian trays required';

COMMENT ON COLUMN "meal_demands"."buffer_rate" IS 'Safety buffer margin between 0.000 and 0.100 (default 5%)';

COMMENT ON COLUMN "meal_demands"."buffer_quantity" IS 'Calculated buffer portions: round(confirmed_attendance * buffer_rate)';

COMMENT ON COLUMN "meal_demands"."final_demand_count" IS 'Total order count: confirmed_attendance + buffer_quantity';

COMMENT ON TABLE "meal_demand_dish_quantities" IS 'Dish-level portion requirements calculated by MenuDishQuantityCalculator';

COMMENT ON COLUMN "meal_demand_dish_quantities"."expected_quantity" IS 'Calculated dish production quantity in kg, liters, or portions';

COMMENT ON TABLE "meal_demand_changes" IS 'Audit log tracking post-calculation adjustments to meal demand';

COMMENT ON TABLE "catering_orders" IS 'Formal purchase order dispatched electronically to the external Catering Vendor before 08:45 AM';

COMMENT ON COLUMN "catering_orders"."order_code" IS 'e.g., PO-20261012-01';

COMMENT ON COLUMN "catering_orders"."target_delivery_time" IS 'Standard dock arrival: 10:30 AM';

COMMENT ON COLUMN "catering_orders"."dispatched_at" IS 'Must execute before 08:45 AM Order Deadline';

COMMENT ON TABLE "meal_deliveries" IS 'Dock receiving record for hot meal shipment delivered by external catering vendor';

COMMENT ON COLUMN "meal_deliveries"."arrival_time" IS 'Recorded when vehicle arrives at school dock (~10:30 AM)';

COMMENT ON COLUMN "meal_deliveries"."vehicle_plate" IS 'Delivery vehicle registration plate number';

COMMENT ON COLUMN "meal_deliveries"."thermal_container_count" IS 'Number of insulated food delivery containers unloaded';

COMMENT ON COLUMN "meal_deliveries"."delivered_portions" IS 'Declared delivered portion count on delivery voucher';

COMMENT ON COLUMN "meal_deliveries"."received_by" IS 'Coordinator receiving the delivery at dock';

COMMENT ON TABLE "meal_inspections" IS 'Statutory 3-step food safety inspection record enforced by QualityInspectionValidator (QĐ 1246/QĐ-BYT)';

COMMENT ON COLUMN "meal_inspections"."inspector_id" IS 'School Nurse or Coordinator executing 3-Step Food Safety Inspection';

COMMENT ON COLUMN "meal_inspections"."core_temperature" IS 'Digital probe thermometer reading in Celsius. Must be >= 65.0 C (Decision 1246/QD-BYT)';

COMMENT ON COLUMN "meal_inspections"."container_seals_intact" IS 'Verification of tamper-evident container seals';

COMMENT ON COLUMN "meal_inspections"."sensory_eval_pass" IS 'Visual, aroma, and texture sensory check';

COMMENT ON COLUMN "meal_inspections"."retention_sample_taken" IS 'Mandatory 24h food retention sample jar sealed and stored';

COMMENT ON COLUMN "meal_inspections"."sample_photo_url" IS 'Photo URL of sealed 24h retention sample jars in S3 store';

COMMENT ON COLUMN "meal_inspections"."thermometer_photo_url" IS 'Photo URL of digital thermometer probe readout in S3 store';

COMMENT ON COLUMN "meal_inspections"."inspected_at" IS 'Completed at 10:30 AM receiving window';

COMMENT ON TABLE "meal_distributions" IS 'Classroom trolley distribution log recording tray quantities dispatched for the 11:00 AM lunch window';

COMMENT ON COLUMN "meal_distributions"."allocated_portions" IS 'Number of meal trays loaded onto classroom trolley';

COMMENT ON COLUMN "meal_distributions"."special_dietary_portions" IS 'Dedicated allergen-free trays for this class';

COMMENT ON COLUMN "meal_distributions"."distributed_at" IS 'Trolley dispatch timestamp (~11:00 AM)';

COMMENT ON TABLE "meal_reconciliations" IS 'Daily 13:00 PM 3-way quantity reconciliation executed by MealReconciliationEngine';

COMMENT ON COLUMN "meal_reconciliations"."ordered_quantity" IS 'Final order headcount sent to caterer at 08:45 AM';

COMMENT ON COLUMN "meal_reconciliations"."delivered_quantity" IS 'Verified portions delivered by caterer at 10:30 AM';

COMMENT ON COLUMN "meal_reconciliations"."consumed_quantity" IS 'Actual portions consumed by present students during lunch';

COMMENT ON COLUMN "meal_reconciliations"."leftover_quantity" IS 'Unserved portions (buffer surplus or absent deductions)';

COMMENT ON COLUMN "meal_reconciliations"."delivery_variance" IS 'delivered_quantity - ordered_quantity';

COMMENT ON COLUMN "meal_reconciliations"."consumption_variance" IS 'consumed_quantity - delivered_quantity';

COMMENT ON COLUMN "meal_reconciliations"."accepted_payable_quantity" IS 'min(ordered_quantity, delivered_and_accepted_quantity) passed to Accountant';

COMMENT ON COLUMN "meal_reconciliations"."reconciled_at" IS 'Post-lunch reconciliation window (~13:00 PM)';

COMMENT ON TABLE "meal_discrepancies" IS 'Mandatory justification and financial resolution log for reconciliation variances';

COMMENT ON COLUMN "meal_discrepancies"."discrepancy_reason" IS 'Mandatory reason, e.g., Vendor Shortfall: 10 meals missing, Spillage during transit';

COMMENT ON COLUMN "meal_discrepancies"."financial_impact_note" IS 'Deducted from vendor invoice / absorbed by school reserve';

COMMENT ON TABLE "meal_fee_configs" IS 'Master meal fee unit price and caterer cost schedule configured by School Accountant';

COMMENT ON COLUMN "meal_fee_configs"."name" IS 'e.g., Bieu phi Ban tru HK1 2026-2027';

COMMENT ON COLUMN "meal_fee_configs"."meal_fee_rate" IS 'Fee charged to parents per lunch meal, e.g., 35000.00 VND';

COMMENT ON COLUMN "meal_fee_configs"."caterer_cost_rate" IS 'Contracted unit cost paid to caterer per meal, e.g., 28000.00 VND';

COMMENT ON TABLE "student_meal_bills" IS 'Monthly student meal bill generated by ChargeableMealBillingCalculator';

COMMENT ON COLUMN "student_meal_bills"."billing_month" IS 'YYYY-MM format, e.g., 2026-10';

COMMENT ON COLUMN "student_meal_bills"."total_scheduled_meals" IS 'Total serving days in month excluding weekends and holidays';

COMMENT ON COLUMN "student_meal_bills"."attended_meals" IS 'Total recorded present meals';

COMMENT ON COLUMN "student_meal_bills"."credited_absences" IS 'Excused absences logged before cutoff refunded/credited';

COMMENT ON COLUMN "student_meal_bills"."unexcused_absences" IS 'Unexcused late absences charged without credit';

COMMENT ON COLUMN "student_meal_bills"."total_chargeable_meals" IS 'attended_meals + unexcused_absences';

COMMENT ON COLUMN "student_meal_bills"."total_amount" IS 'total_chargeable_meals * unit_price';

COMMENT ON COLUMN "student_meal_bills"."vietqr_payload" IS 'Dynamic VietQR payment payload containing invoice ID and exact amount';

COMMENT ON TABLE "student_billing_items" IS 'Itemized day-by-day audit trail demonstrating why each lunch date was billed or credited';

COMMENT ON COLUMN "student_billing_items"."credit_reason" IS 'Excused absence credited / School holiday';

COMMENT ON TABLE "meal_payments" IS 'Payment transaction recording parent fee settlements across 3 streamlined states';

COMMENT ON COLUMN "meal_payments"."payment_code" IS 'Receipt / transaction reference code';

COMMENT ON COLUMN "meal_payments"."transaction_reference" IS 'Banking transaction reference from VietQR payment webhook';

COMMENT ON COLUMN "meal_payments"."recorded_by" IS 'Accountant user ID or system webhook user';

COMMENT ON TABLE "vendor_payables" IS 'Accrued caterer liabilities derived by VendorCostPayableAccrualService based on reconciled deliveries';

COMMENT ON COLUMN "vendor_payables"."reconciled_billable_portions" IS 'accepted_payable_quantity from meal_reconciliations';

COMMENT ON COLUMN "vendor_payables"."unit_cost" IS 'Contracted cost rate from meal_fee_configs';

COMMENT ON COLUMN "vendor_payables"."total_payable_amount" IS 'reconciled_billable_portions * unit_cost';

ALTER TABLE "semesters" ADD FOREIGN KEY ("school_year_id") REFERENCES "school_years" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "classes" ADD FOREIGN KEY ("school_year_id") REFERENCES "school_years" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "classes" ADD FOREIGN KEY ("grade_id") REFERENCES "grades" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "students" ADD FOREIGN KEY ("current_class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "holidays" ADD FOREIGN KEY ("school_year_id") REFERENCES "school_years" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "classes" ADD FOREIGN KEY ("homeroom_teacher_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "parent_student_associations" ADD FOREIGN KEY ("parent_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "parent_student_associations" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_allergies" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dish_ingredients" ADD FOREIGN KEY ("dish_id") REFERENCES "dishes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dish_ingredients" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menus" ADD FOREIGN KEY ("school_year_id") REFERENCES "school_years" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menus" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menus" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_dishes" ADD FOREIGN KEY ("menu_id") REFERENCES "menus" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_dishes" ADD FOREIGN KEY ("dish_id") REFERENCES "dishes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_schedules" ADD FOREIGN KEY ("menu_id") REFERENCES "menus" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_eligibility_criteria" ADD FOREIGN KEY ("school_year_id") REFERENCES "school_years" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_meal_eligibilities" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_meal_eligibilities" ADD FOREIGN KEY ("criteria_id") REFERENCES "meal_eligibility_criteria" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_meal_eligibilities" ADD FOREIGN KEY ("verified_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_registrations" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_registrations" ADD FOREIGN KEY ("semester_id") REFERENCES "semesters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_registrations" ADD FOREIGN KEY ("registered_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("meal_schedule_id") REFERENCES "meal_schedules" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("meal_registration_id") REFERENCES "meal_registrations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participations" ADD FOREIGN KEY ("recorded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participation_changes" ADD FOREIGN KEY ("meal_participation_id") REFERENCES "meal_participations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_participation_changes" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demands" ADD FOREIGN KEY ("meal_schedule_id") REFERENCES "meal_schedules" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demands" ADD FOREIGN KEY ("determined_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demands" ADD FOREIGN KEY ("confirmed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_dish_quantities" ADD FOREIGN KEY ("meal_demand_id") REFERENCES "meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_dish_quantities" ADD FOREIGN KEY ("dish_id") REFERENCES "dishes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_changes" ADD FOREIGN KEY ("meal_demand_id") REFERENCES "meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_demand_changes" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "catering_orders" ADD FOREIGN KEY ("meal_demand_id") REFERENCES "meal_demands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "catering_orders" ADD FOREIGN KEY ("dispatched_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_deliveries" ADD FOREIGN KEY ("catering_order_id") REFERENCES "catering_orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_deliveries" ADD FOREIGN KEY ("received_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_inspections" ADD FOREIGN KEY ("meal_delivery_id") REFERENCES "meal_deliveries" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_inspections" ADD FOREIGN KEY ("inspector_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_distributions" ADD FOREIGN KEY ("meal_delivery_id") REFERENCES "meal_deliveries" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_distributions" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_distributions" ADD FOREIGN KEY ("distributed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_distributions" ADD FOREIGN KEY ("received_by_teacher_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_reconciliations" ADD FOREIGN KEY ("catering_order_id") REFERENCES "catering_orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_reconciliations" ADD FOREIGN KEY ("reconciled_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_discrepancies" ADD FOREIGN KEY ("meal_reconciliation_id") REFERENCES "meal_reconciliations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_discrepancies" ADD FOREIGN KEY ("resolved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_fee_configs" ADD FOREIGN KEY ("school_year_id") REFERENCES "school_years" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_fee_configs" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_meal_bills" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_meal_bills" ADD FOREIGN KEY ("fee_config_id") REFERENCES "meal_fee_configs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_billing_items" ADD FOREIGN KEY ("student_meal_bill_id") REFERENCES "student_meal_bills" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_billing_items" ADD FOREIGN KEY ("meal_schedule_id") REFERENCES "meal_schedules" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_billing_items" ADD FOREIGN KEY ("meal_participation_id") REFERENCES "meal_participations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_payments" ADD FOREIGN KEY ("student_meal_bill_id") REFERENCES "student_meal_bills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "meal_payments" ADD FOREIGN KEY ("recorded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vendor_payables" ADD FOREIGN KEY ("fee_config_id") REFERENCES "meal_fee_configs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vendor_payables" ADD FOREIGN KEY ("catering_order_id") REFERENCES "catering_orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;
